default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: family_to_do_list_development

test:
  <<: *default
  database: family_to_do_list_test

production:
  <<: *default
